spring:
  mail:
    default-encoding: utf-8
    host: smtp.gmail.com
    username: jourdyhuamanchuchon@gmail.com
    password: ksdeasqusmywcoba
    port: 587
    properties:
      mail:
        ssl:
          enable: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: false
